version: '3'

services:
  db:
    image: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=fpafullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - des2-mysql-app

  app:
    image: openjdk:8-jdk-alpine
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - des2-mysql-app
      - des2-nginx-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s java -jar ./app.jar
    tty: true
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.20.0-alpine
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    entrypoint: dockerize -wait http://app:8086 -timeout 20s ./docker-entrypoint.sh nginx -g "daemon off;"
    #command: nginx -g "daemon off;"
    ports: 
      - 8000:8080
    networks: 
      - des2-nginx-app
    restart: always
    depends_on:
    - app
  

networks:
  des2-mysql-app:
    driver: bridge
  des2-nginx-app:
    driver: bridge
